### ISSUE TITLE
Header bar remains in dark mode, when light mode is enabled

### ISSUE THREAD

**Issue by RuboGubo** [DiscordStyles/Slate#109]
### Describe the bug
Header bar remains in dark mode, when light mode is enabled

### To Reproduce  
Go to light mode from the settings panel.

### Screenshots
![image](https://user-images.githubusercontent.com/73720453/181294845-f43b376b-4e99-494c-9b1a-224a35dd1756.png)

### Information (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Linux*
**Mod**: *BetterDiscord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
This is not a bug, but by design. Screenshot from the GitHub desktop client:

![image](https://user-images.githubusercontent.com/20338746/181404966-f29d1075-0c08-40b4-8efa-6f2c74b512e5.png)

You can change it by editing the variables: https://github.com/DiscordStyles/Slate/wiki/Hidden-Variables#toolbar-fixed-dark-mode-vars
