### ISSUE TITLE
Dislocated buttons and missing space on English UK

### ISSUE THREAD

**Issue by MegaHello** [DiscordStyles/Slate#59]
**Describe the bug**  
Inbox is missing, pins is in the wrong spot and the status changer is also dislocated
There also seems to be a lot of empty space in the top bar near the search bar.
Seems to be related to the language setting.

**To Reproduce**  
Change language to English UK.
*(Better to reload)*

**Screenshots**  
**English UK** *(where the icons are dislocated)*
[Screenshot](https://megahello.s-ul.eu/TdVq0aKr)

**English US**
[Screenshot](https://megahello.s-ul.eu/gCfyPvDO)
*did not notice the status changer was also misplaced until i took this screenshot*
*thats why theres no text in the previous screenshot*

**Infomation (please complete the following information):**  
Discord channel: **Canary**  
OS: **Windows**  
Mod: **Powercord**  
Discord language: **English UK**  

**Additional context**  
A simple fix for now is to change your language to English US

**Comment by Gibbu** [comment]
The reason for this is because setting up the buttons (as seen in the English US) is a pain in the ass.
We have to get every string from every language and then position them individually.

This is JUST for English US: https://github.com/DiscordStyles/Slate/blob/master/src/app/_toolbar.scss#L331
And this is the compiled css: https://github.com/DiscordStyles/Slate/blob/master/dist/Slate.css#L727

**Comment by Gibbu** [comment]
Also, not sure why you get weird spacing issues. I'm perfectly fine on both languages.
![image](https://user-images.githubusercontent.com/20338746/128583692-f89bce7d-ea8b-4449-9c5d-ff1eb252b653.png)

**Comment by MegaHello** [comment]
Yeah, I got the missing space fixed after reloading. Understandable, could you add on the github page something along these lines.

*For the time being the language supported is English US. Every other language may cause unintended side effects.*
