### ISSUE TITLE
GIF search menus do not scroll down all the way

### ISSUE THREAD

**Issue by NickHam13** [DiscordStyles/Slate#85]
**Describe the bug**  
When opening the GIF search tab, the scroll bar only scrolls a little bit before it stops completely, leaving you unable to look at all of the available GIFs. When the theme is disabled, you can scroll down all the way.

**Information (please complete the following information):**  
Discord channel: Canary
OS: Windows
Mod: Powercord
Discord language: English

**Comment by rinustechtips** [comment]
Am having this problem too.

**Comment by silensshadow** [comment]
same, i have this problem too

**Comment by souxd** [comment]
im having the same issue 

Information (please complete the following information):
Discord channel: Stable
OS: Linux
Mod: BetterDiscord
Discord language: English

**Comment by falt4** [comment]
This issue was not fixed. The search menu is fine, but when you go into an individual category (say Favourites), only a few of the gifs at the top appear, and you can only scroll down a tiny bit. The exact problem that the OP described. I can also confirm that this does work without the theme enabled.

Information
Discord channel: Stable
OS: Windows 10
Mod: BetterDiscord
Discord language: English

**Comment by NickHam13** [comment]
I can also confirm this behavior still occurs.
